void backpatch(struct sem_rec *, int);
void bgnstmt();
struct sem_rec *call(char *, struct sem_rec *);
struct sem_rec *cast(struct sem_rec *, int);
struct sem_rec *ccand(struct sem_rec *, int, struct sem_rec *);
struct sem_rec *ccexpr(struct sem_rec *);
struct sem_rec *ccnot(struct sem_rec *);
struct sem_rec *ccor(struct sem_rec *, int, struct sem_rec *);
struct sem_rec *con(char *);
void dobreak();
void docontinue();
void dodo(int, int, struct sem_rec *, int);
void dofor(int, struct sem_rec *, int, struct sem_rec *, int,
           struct sem_rec *, int);
void dogoto(char *);
void doif(struct sem_rec *, int, int);
void doifelse(struct sem_rec *, int, struct sem_rec *, int, int);
void doret(struct sem_rec *);
void dowhile(int m1, struct sem_rec *, int, struct sem_rec *, int);
void endloopscope(int);
struct sem_rec *exprs(struct sem_rec *, struct sem_rec *);
void fhead(struct id_entry *);
struct id_entry *fname(int, char *);
void ftail();
struct sem_rec *gen(char *, struct sem_rec *, struct sem_rec *, int);
struct sem_rec *id(char *);
struct sem_rec *tom_index(struct sem_rec *x, struct sem_rec *i);
void labeldcl(char *);
int m();
struct sem_rec *n();
struct sem_rec *op1(char *, struct sem_rec *);
struct sem_rec *op2(char *, struct sem_rec *, struct sem_rec *);
struct sem_rec *opb(char *, struct sem_rec *, struct sem_rec *);
struct sem_rec *rel(char *, struct sem_rec *, struct sem_rec *);
struct sem_rec *set(char *, struct sem_rec *, struct sem_rec *);
void startloopscope();
struct sem_rec *string(char *);
